cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://springudemypedro.com.br
file:
  upload-dir: /Users/Tattu/Desktop/upload
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
      username: root
      password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB 
      max-request-size: 215MB                
springdoc:
  paths-to-match:
    - /auth/** 
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true